
//#define MATRIX_ROW_PINS { D1, B5, B4, F4, B1, B6 }
#undef MATRIX_COL_PINS
#define MATRIX_COL_PINS { F5, F7, B2, C6, D7, E6 }

#define MOUSEKEY_DELAY 10
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_MAX_SPEED 1
#define MOUSEKEY_TIME_TO_MAX 20

#define MOUSEKEY_WHEEL_DENAY 30
#define MOUSEKEY_WHEEL_INTERVAL 10
#define MOUSEKEY_WHEEL_MAX_SPEED 1
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0
